[tools]
node = '24'
rust = "latest"
"github:aliev/baker" = "latest"
"cargo:cargo-chef" = "latest"
pnpm = "latest"

[tasks.generate]
description = "Generate the project files"
run = "baker . ./generated/$ANSWER --answers-file samples/answers-$ANSWER.json --force --non-interactive --skip-confirms all"

[tasks.frontend]
description = "Build frontend"
run = '''
cd ./generated/$ANSWER/frontend
pnpm install --no-frozen-lockfile
pnpm run build
'''
depends = ["generate"]

[tasks.build]
description = "Build the project"
run = '''
cd ./generated/$ANSWER
cargo update
cargo build --release
'''

[tasks.test]
description = "Run tests"
run = '''
cd ./generated/$ANSWER
cargo test
'''
depends = ["build"]

[tasks.e2e]
description = "Run e2e tests"
run = '''
cd ./generated/$ANSWER/e2e
cargo test
'''
depends = ["test"]

[tasks.rest]
description = "Generate and build rest sample"
env.ANSWER = "rest"
run = ["mise run generate", "mise run test"]

[tasks.rest-jwt]
description = "Generate and build rest-jwt sample"
env.ANSWER = "rest-jwt"
run = ["mise run generate", "mise run test"]

[tasks.rest-shadcn]
description = "Generate and build rest-shadcn sample"
env.ANSWER = "rest-shadcn"
run = ["mise run frontend", "mise run e2e"]

[tasks.grpc]
description = "Generate and build grpc sample"
env.ANSWER = "grpc"
run = ["mise run generate", "mise run test"]

[tasks.all]
description = "Generate and build all samples"
run = ["mise run test", "mise run test rest-jwt", "mise run test rest-shadcn", "mise run test grpc"]